apiVersion: v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
  volumes:
    - name: pv-postgres
      persistentVolumeClaim:
        claimName: pvc-postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: test
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: test
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pv-postgres
      