apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
   matchLabels:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: test
        - name: POSTGRES_USER
          value: test
        - name: POSTGRES_PASSWORD
          value: test
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: pv-postgres
      volumes:
      - name: pv-postgres
        persistentVolumeClaim:
          claimName: pvc-postgres
